//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppointmentSystem.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOINTMENT_NOTE
    {
        public int PRECRIPTIONID { get; set; }
        public int APPOINTMENTID { get; set; }
        public string NOTE { get; set; }
    
        public virtual PRESCRIPTION PRESCRIPTION { get; set; }
        public virtual APPOINTMENT APPOINTMENT { get; set; }
    }
}
