//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppointmentSystem.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.DOCTORs = new HashSet<DOCTOR>();
            this.PATIENTs = new HashSet<PATIENT>();
        }
    
        public int USERID { get; set; }
        public int ROLEID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORDHASH { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> LASTLOGIN { get; set; }
        public string USERTYPE { get; set; }
        public byte[] AVATARURL { get; set; }
        public string PASSWORDRECOVERY1 { get; set; }
        public string PASSWORDRECOVERY2 { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> LOGINRETRYCOUNT { get; set; }
        public Nullable<System.DateTime> LOGINLOCKDATE { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string UPDATEDBY { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public bool DELETEDFLAG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTOR> DOCTORs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PATIENT> PATIENTs { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
